name: GoldToolUtils
main: com.garsooon.goldtoolsutil.GoldToolUtils
version: ${project.version}
authors: [Garsooon, BetaMC Developers]
description: Simple lightweight plugin that adds special effects to gold tools over the weekend
website: https://github.com/BetaMC-Developers/GoldToolUtils